name: Markdown lint & linkcheck

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli@0.31.0
      - name: Run markdownlint
        run: |
          # ignore node_modules and vendor folders
          markdownlint "**/*.md" --ignore node_modules || true
      - name: Run linkcheck (lychee)
        uses: lycheeverse/lychee-action@v2
        with:
          args: '--no-progress --timeout 10'
